version: "3.8"

services:
  blue:
    container_name: blue
    profiles: [blue]
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - deploynet

  green:
    container_name: green
    profiles: [green]
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - deploynet

  app:
    image: nginx:1.27-alpine
    container_name: app
    profiles: [blue, green]
    ports:
      - "80:80"
    volumes:
      - ./deployer/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deployer/active_backend.conf:/etc/nginx/conf.d/active_backend.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - deploynet

networks:
  deploynet:
    driver: bridge
